import { CanvasNode, CanvasEdge } from '../types/canvas';
import { WebMCPToolDefinition } from '../types/webmcp';

export function exportWebMCPManifest(tools: WebMCPToolDefinition[]): string {
  const manifest = {
    $schema: 'https://spec.webmcp.org/v1/schema.json',
    title: 'AgentStudio WebMCP Toolset',
    version: '1.0.0',
    description: 'Tools registered on document.modelContext for OpenAI ChatGPT & Chrome 149+ browsers',
    tools: tools.map((t) => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
      requiresConfirmation: t.requiresConfirmation || false,
      category: t.category || 'general',
    })),
  };
  return JSON.stringify(manifest, null, 2);
}

export function exportWorkspaceJSON(nodes: CanvasNode[], edges: CanvasEdge[]): string {
  return JSON.stringify({ nodes, edges, exportedAt: new Date().toISOString() }, null, 2);
}

export function exportStandaloneHTML(nodes: CanvasNode[], tools: WebMCPToolDefinition[]): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AgentStudio Standalone Export</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-slate-100 p-8">
  <div class="max-w-6xl mx-auto space-y-8">
    <header class="border-b border-slate-800 pb-4 flex justify-between items-center">
      <div>
        <h1 class="text-3xl font-bold text-cyan-400">AgentStudio WebMCP Export</h1>
        <p class="text-slate-400 text-sm">Autonomous WebMCP Canvas Snapshot</p>
      </div>
      <span class="px-3 py-1 bg-cyan-500/20 text-cyan-300 rounded-full text-xs font-mono">
        ${tools.length} WebMCP Tools Active
      </span>
    </header>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      ${nodes
        .map(
          (n) => `
        <div class="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl">
          <div class="flex items-center justify-between mb-3">
            <span class="text-xs font-mono uppercase text-cyan-400 font-semibold">${n.type}</span>
            <span class="text-xs text-slate-500">ID: ${n.id}</span>
          </div>
          <h2 class="text-xl font-bold text-white mb-2">${n.data.title}</h2>
          <p class="text-sm text-slate-300">${n.data.description || ''}</p>
        </div>`
        )
        .join('\n')}
    </div>

    <footer class="text-center text-xs text-slate-600 pt-8 border-t border-slate-800">
      Generated by AgentStudio — Powered by WebMCP Open Protocol Standard
    </footer>
  </div>

  <script>
    // WebMCP Registration in Standalone Export
    if (typeof document !== 'undefined') {
      console.log('WebMCP Standalone initialized with registered tools');
    }
  </script>
</body>
</html>`;
}
